name: build
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELASE_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: '${{ steps.extract-release-notes.outputs.release_notes }}'
  build_android:
    name: build_android
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
      - run: flutter --version
      - name: Setup keystore
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 --decode > android/app/Aprdec.keystore
          echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties
      - name: build
        run: |
          flutter pub get
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: Pack Android apk
        run: |
          pushd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release.apk HNDcharge-arm64_v8a.apk
          mv app-armeabi-v7a-release.apk HNDcharge_armeabi_v7a.apk
          popd
      - name: Release Android artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          artifacts: 'build/app/outputs/flutter-apk/HNDcharge-arm64_v8a.apk,build/app/outputs/flutter-apk/HNDcharge_armeabi_v7a.apk'
