name: build_test
on:
  workflow_dispatch:
    inputs:
      build_android:
        description: Build Android platform artifacts.
        required: true
        type: boolean
        default: true
      dry_run:
        description: Dry run, do NOT upload artifacts.
        required: true
        type: boolean
        default: true
jobs:
  build_android:
    name: build_android
    if: ${{ github.event_name == 'push' || inputs.build_android }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
      - run: flutter --version
      - name: Setup keystore
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 --decode > android/app/Aprdec.keystore
          echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties
      - name: build
        run: |
          flutter pub get
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: Pack Android apk
        run: |
          pushd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release.apk HNDcharge-arm64_v8a.apk
          mv app-armeabi-v7a-release.apk HNDcharge_armeabi_v7a.apk
          popd
      - name: Upload Android artifacts
        if: ${{ github.event_name != 'push' && inputs.build_android && !inputs.dry_run }}
        uses: actions/upload-artifact@v4
        with:
          name: HNDcharge-arm64_v8a
          path: |
            build/app/outputs/flutter-apk/HNDcharge-arm64_v8a.apk